version: '2'
services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=somewhatsecretpassword
      - POSTGRES_DB=spacedock
  redis:
    restart: always
    image: redis:latest
  spacedock:
    restart: always
    image: spacedock.info:5550/spacedock:latest
    env_file: deployment_settings.cfg
    environment:
      - USE_GUNICORN=true
    volumes:
      - /opt/spacedock/static
      - /opt/spacedock/storage
    expose:
      - "5000"
    links:
      - db
      - redis
  nginx:
    restart: always
    image: spacedock.info:5550/nginx:latest
    ports:
      - "127.0.0.1:22045:80"
    volumes_from:
      - spacedock
    links:
      - spacedock
